#include <bits/stdc++.h>
using namespace std; using ll=long long;
const int MOD=998244353,G=3;
int power(int a,int e){ll r=1;for(;e;e>>=1,a=(ll)a*a%MOD)if(e&1)r=r*a%MOD;return r;}
void ntt(vector<int>&a,bool inv){int n=a.size();for(int i=1,j=0;i<n;i++){int b=n>>1;for(;j&b;b>>=1)j^=b;j^=b;if(i<j)swap(a[i],a[j]);}for(int len=2;len<=n;len<<=1){int wlen=power(G,(MOD-1)/len);if(inv)wlen=power(wlen,MOD-2);for(int i=0;i<n;i+=len){ll w=1;for(int j=0;j<len/2;j++){int u=a[i+j],v=w*a[i+j+len/2]%MOD;a[i+j]=u+v;if(a[i+j]>=MOD)a[i+j]-=MOD;a[i+j+len/2]=u-v;if(a[i+j+len/2]<0)a[i+j+len/2]+=MOD;w=w*wlen%MOD;}}}if(inv){ll z=power(n,MOD-2);for(int&x:a)x=x*z%MOD;}}
vector<int> conv(vector<int>a,vector<int>b,int need=-1){if(a.empty()||b.empty())return{};int total=a.size()+b.size()-1;if(min(a.size(),b.size())<32){vector<int>c(total);for(int i=0;i<(int)a.size();i++)for(int j=0;j<(int)b.size();j++)c[i+j]=(c[i+j]+(ll)a[i]*b[j])%MOD;if(need>=0&&need<(int)c.size())c.resize(need);return c;}int n=1;while(n<total)n<<=1;a.resize(n);b.resize(n);ntt(a,0);ntt(b,0);for(int i=0;i<n;i++)a[i]=(ll)a[i]*b[i]%MOD;ntt(a,1);a.resize(need>=0?min(need,total):total);return a;}
vector<int> inverse(const vector<int>&a,int n){vector<int>r(1,power(a[0],MOD-2));for(int sz=2;sz/2<n;sz<<=1){int take=min(sz,n);vector<int>f(a.begin(),a.begin()+min((int)a.size(),take));auto t=conv(f,r,take);t.resize(take);t[0]=(2-t[0]+MOD)%MOD;for(int i=1;i<take;i++)if(t[i])t[i]=MOD-t[i];r=conv(r,t,take);r.resize(take);}r.resize(n);return r;}
vector<int> derivative(const vector<int>&a){vector<int>d(max(0,(int)a.size()-1));for(int i=1;i<(int)a.size();i++)d[i-1]=(ll)i*a[i]%MOD;return d;}
vector<int> integrate(const vector<int>&a){vector<int>r(a.size()+1),iv(a.size()+1);if(a.size())iv[1]=1;for(int i=2;i<(int)iv.size();i++)iv[i]=MOD-(ll)(MOD/i)*iv[MOD%i]%MOD;for(int i=1;i<(int)r.size();i++)r[i]=(ll)a[i-1]*iv[i]%MOD;return r;}
vector<int> logarithm(const vector<int>&a,int n){auto r=integrate(conv(derivative(a),inverse(a,n),n-1));r.resize(n);return r;}
vector<int> exponential(const vector<int>&a,int n){vector<int>r(1,1);for(int sz=2;sz/2<n;sz<<=1){int take=min(sz,n);auto lg=logarithm(r,take);vector<int>d(take);for(int i=0;i<take;i++)d[i]=((i<(int)a.size()?a[i]:0)-lg[i]+MOD)%MOD;d[0]++;if(d[0]>=MOD)d[0]-=MOD;r=conv(r,d,take);r.resize(take);}r.resize(n);return r;}
vector<int> square_root(const vector<int>&a,int n){vector<int>r(1,1);int half=(MOD+1)/2;for(int sz=2;sz/2<n;sz<<=1){int take=min(sz,n);vector<int>f(a.begin(),a.begin()+min((int)a.size(),take));auto q=conv(f,inverse(r,take),take);q.resize(take);r.resize(take);for(int i=0;i<take;i++)r[i]=(ll)(r[i]+q[i])*half%MOD;}r.resize(n);return r;}
void trim(vector<int>&a){while(!a.empty()&&a.back()==0)a.pop_back();}
vector<int> poly_mod(vector<int>a,vector<int>b){trim(a);trim(b);if(a.size()<b.size())return a;vector<int>orig=a;int qn=a.size()-b.size()+1;reverse(a.begin(),a.end());reverse(b.begin(),b.end());a.resize(qn);auto q=conv(a,inverse(b,qn),qn);reverse(q.begin(),q.end());reverse(b.begin(),b.end());auto p=conv(q,b);vector<int>r(b.size()-1);for(int i=0;i<(int)r.size();i++)r[i]=(orig[i]-(i<(int)p.size()?p[i]:0)+MOD)%MOD;trim(r);return r;}
struct ProductTree{int n,size;vector<int>x;vector<vector<int>>t;ProductTree(vector<int>xs):n(xs.size()),x(move(xs)){size=1;while(size<n)size<<=1;t.assign(2*size,{1});for(int i=0;i<n;i++)t[size+i]={x[i]?MOD-x[i]:0,1};for(int i=size-1;i;i--)t[i]=conv(t[i<<1],t[i<<1|1]);}
 vector<int> eval(const vector<int>&a){vector<int>ans(n);function<void(int,vector<int>)>go=[&](int v,vector<int>r){if(v>=size){int i=v-size;if(i<n)ans[i]=r.empty()?0:r[0];return;}go(v<<1,poly_mod(r,t[v<<1]));go(v<<1|1,poly_mod(r,t[v<<1|1]));};go(1,poly_mod(a,t[1]));return ans;}
 vector<int> interp(const vector<int>&y){auto val=eval(derivative(t[1]));vector<vector<int>>w(2*size,vector<int>{0});for(int i=0;i<n;i++)w[size+i]={(int)((ll)y[i]*power(val[i],MOD-2)%MOD)};for(int v=size-1;v;v--){w[v]=conv(w[v<<1],t[v<<1|1]);auto z=conv(w[v<<1|1],t[v<<1]);w[v].resize(max(w[v].size(),z.size()));for(int i=0;i<(int)z.size();i++){w[v][i]+=z[i];if(w[v][i]>=MOD)w[v][i]-=MOD;}}w[1].resize(n);return w[1];}};
void fwt(vector<int>&a,string kind,bool inv=false){int n=a.size();for(int bit=1;bit<n;bit<<=1)for(int s=0;s<n;s++)if(s&bit){if(kind=="or"){a[s]=(a[s]+(inv?MOD-a[s^bit]:a[s^bit]))%MOD;}else{int u=a[s^bit],v=a[s];a[s^bit]=u+v;if(a[s^bit]>=MOD)a[s^bit]-=MOD;a[s]=u-v;if(a[s]<0)a[s]+=MOD;}}if(kind=="xor"&&inv){ll z=power(n,MOD-2);for(int&v:a)v=v*z%MOD;}}
vector<int> subset_conv(const vector<int>&f,const vector<int>&g,int k){int n=1<<k;vector<vector<int>>F(k+1,vector<int>(n)),H=F,Gv=F;for(int s=0;s<n;s++){int c=__builtin_popcount(s);F[c][s]=f[s];Gv[c][s]=g[s];}for(int bit=0;bit<k;bit++)for(int s=0;s<n;s++)if(s>>bit&1)for(int c=0;c<=k;c++){F[c][s]+=F[c][s^(1<<bit)];if(F[c][s]>=MOD)F[c][s]-=MOD;Gv[c][s]+=Gv[c][s^(1<<bit)];if(Gv[c][s]>=MOD)Gv[c][s]-=MOD;}for(int s=0;s<n;s++)for(int c=0;c<=k;c++)for(int i=0;i<=c;i++)H[c][s]=(H[c][s]+(ll)F[i][s]*Gv[c-i][s])%MOD;for(int bit=0;bit<k;bit++)for(int s=0;s<n;s++)if(s>>bit&1)for(int c=0;c<=k;c++){H[c][s]-=H[c][s^(1<<bit)];if(H[c][s]<0)H[c][s]+=MOD;}vector<int>ans(n);for(int s=0;s<n;s++)ans[s]=H[__builtin_popcount(s)][s];return ans;}
void print(const vector<int>&a){for(int i=0;i<(int)a.size();i++)cout<<a[i]<<" \n"[i+1==(int)a.size()];}
int main(){ios::sync_with_stdio(false);cin.tie(nullptr);int n;cin>>n;vector<int>x(n),y(n);for(int i=0;i<n;i++)cin>>x[i]>>y[i];ProductTree tree(x);print(tree.interp(y));}
