from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.section_checker import run_section_checks

SECTION = Path(__file__).resolve().parent
PROBLEMS = [SECTION / "problems" / name for name in (
    "01_temporal_path_median",
    "02_bipartite_timeline",
    "03_versioned_convex_dp",
    "04_historical_rectangle_selection",
    "05_dynamic_forest_ledger",
    "06_colored_distance_census",
    "07_virtual_tree_firewall",
    "08_subtree_order_laboratory",
    "09_ancestral_pattern_index",
    "10_kruskal_time_machine",
    "11_bounded_convex_shipping",
    "12_parametric_quota_cut",
    "13_rainbow_bottleneck_forest",
    "14_rooted_broadcast_choice",
    "15_pairing_under_thresholds",
    "16_all_pairs_cut_statistics",
    "17_isotonic_tree_labels",
    "18_circulation_repair_queries",
    "19_convex_resource_schedule",
    "20_laminar_assignment",
    "21_persistent_text_occurrences",
    "22_multi_archive_common_substrings",
    "23_palindromic_range_census",
    "24_lexicographic_substring_laboratory",
    "25_dynamic_pattern_ledger",
    "26_cyclic_match_convolution",
    "27_distinct_substring_rank",
    "28_interval_lcp_aggregates",
    "29_editable_palindrome_rope",
    "30_forbidden_superstring_count",
    "31_two_faction_networks",
    "32_exponential_polynomial_ledger",
    "33_branching_family_census",
    "34_coin_bag_census",
    "35_staircase_moments",
    "36_binomial_ledger",
    "37_rabbit_cycle",
    "38_exclusive_range_ledger",
    "39_divisor_echo_power",
    "40_root_census_modulo_p",
    "41_sprinkler_coverage_area",
    "42_crystal_hull_surface",
    "43_triangle_census_queries",
    "44_polygon_triangulation_count",
    "45_obstacle_shortcut",
    "46_lantern_grid",
    "47_quorum_circle",
    "48_quiet_committee_census",
    "49_glacier_cut",
    "50_chronicle_path_dictionary",
    "51_echo_census",
    "52_tariff_revision_network",
    "53_spanning_weight_spectrum",
    "54_fleet_pairing",
    "55_monsoon_diameter",
    "56_window_substring_census",
    "57_prime_power_xor_sum",
    "58_critical_link_audit",
    "59_walk_count_oracle",
    "60_taxicab_backbone",
    "61_cavern_descent",
    "62_window_component_census",
    "63_periodic_loop_frontier",
    "64_beacon_placement",
    "65_temporal_steiner_span",
)]

if __name__ == "__main__":
    raise SystemExit(run_section_checks(100, PROBLEMS, ROOT))
