from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.section_checker import run_section_checks

SECTION = Path(__file__).resolve().parent
PROBLEMS = [SECTION / "problems" / name for name in (
    "01_temporal_path_median",
    "02_bipartite_timeline",
    "03_versioned_convex_dp",
    "04_historical_rectangle_selection",
    "05_dynamic_forest_ledger",
    "06_colored_distance_census",
    "07_virtual_tree_firewall",
    "08_subtree_order_laboratory",
    "09_ancestral_pattern_index",
    "10_kruskal_time_machine",
    "11_bounded_convex_shipping",
    "12_parametric_quota_cut",
    "13_rainbow_bottleneck_forest",
    "14_rooted_broadcast_choice",
    "15_pairing_under_thresholds",
    "16_all_pairs_cut_statistics",
    "17_isotonic_tree_labels",
    "18_circulation_repair_queries",
    "19_convex_resource_schedule",
    "20_laminar_assignment",
    "21_persistent_text_occurrences",
    "22_multi_archive_common_substrings",
    "23_palindromic_range_census",
    "24_lexicographic_substring_laboratory",
    "25_dynamic_pattern_ledger",
    "26_cyclic_match_convolution",
    "27_distinct_substring_rank",
    "28_interval_lcp_aggregates",
    "29_editable_palindrome_rope",
    "30_forbidden_superstring_count",
    "31_connected_structure_series",
    "32_rational_recurrence_samples",
    "33_subset_partition_spectrum",
    "34_xor_walk_spectrum",
    "35_polynomial_constraint_recovery",
    "36_factorized_exponent_tower",
    "37_modular_root_catalogue",
    "38_composite_discrete_log",
    "39_summatory_multiplicative_blocks",
    "40_gcd_convolution_queries",
    "41_moving_convex_robots",
    "42_safe_radius_region",
    "43_circle_network_bottleneck",
    "44_rectangle_coverage_moments",
    "45_offline_dynamic_hull_queries",
    "46_digit_language_arithmetic",
    "47_periodic_connected_tiling",
    "48_prize_steiner_frontier",
    "49_treewidth_connected_cover",
    "50_chronicle_path_dictionary",
    "51_versioned_path_pattern_census",
    "52_temporal_geometric_alliances",
    "53_colored_cut_tree_summaries",
    "54_exact_fleet_circulation",
    "55_palindromic_paths_through_centroids",
    "56_congruent_substring_selection",
    "57_polynomial_tree_colorings",
    "58_multiplicative_set_partitions",
    "59_factorized_recurrence_oracle",
    "60_delaunay_terminal_backbone",
    "61_moving_half_plane_assignment",
    "62_historical_rectangle_quantiles",
    "63_periodic_forbidden_frontier",
    "64_connected_cover_on_bags",
    "65_temporal_steiner_dictionary",
)]

if __name__ == "__main__":
    raise SystemExit(run_section_checks(100, PROBLEMS, ROOT))
